#!/bin/python3

import math
import os
import random
import re
import sys


import requests
#
# Complete the 'getTotalGoals' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING team
#  2. INTEGER year
#

def getTotalGoals(team, year):
    # Write your code here
    a=0
    request=requests.get('https://jsonmock.hackerrank.com/api/football_matches?year='+str(year)+'&team1='+str(team)+'&page=1').json()
    total=request['total_pages']
    perpage=request['per_page']
    for j in range(1,total+1):
         request=requests.get('https://jsonmock.hackerrank.com/api/football_matches?year='+str(year)+'&team1='+str(team)+'&page='+str(j)).json()
         try:
            for i in range(0,perpage):
                team1=request['data'][i]['team1goals']
                a+=int(team1)
         except:
            pass

        
    request1=requests.get('https://jsonmock.hackerrank.com/api/football_matches?year='+str(year)+'&team2='+str(team)+'&page=1').json()
    total1=request1['total_pages']
    perpage=request['per_page']
    for j in range(1,total1+1):
         request1=requests.get('https://jsonmock.hackerrank.com/api/football_matches?year='+str(year)+'&team2='+str(team)+'&page='+str(j)).json()
         try:
            for i in range(0,perpage):
                team2=request1['data'][i]['team2goals']
                a+=int(team2)
         except:
            pass
    return a

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    team = input()

    year = int(input().strip())

    result = getTotalGoals(team, year)

    fptr.write(str(result) + '\n')

    fptr.close()
